version: '3'
services:
  ngnix-ui:
    image: uozi/nginx-ui:latest
    container_name: ngnix-ui
    restart: always
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - /var/www:/var/www
      - /etc/nginx:/etc/nginx
      - ./data/nginx-ui:/etc/nginx-ui