version: '3.8'
services:
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    container_name: nginx-proxy-manager
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - nginx-proxy-manager:/data
      - nginx-proxy-manager:/etc/letsencrypt

volumes:
  nginx-proxy-manager: ~